version: "3.7"

services:
  # Redis Server
  redis:
    container_name: redis
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "classvar"

  # Redis Web-UI
  # https://hub.docker.com/r/rediscommander/redis-commander
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=classvar
      - HTTP_USER=classvar
      - HTTP_PASSWORD=classvar
    ports:
      - "8081:8081"
    depends_on:
      - redis
